version: '3.8'
#Volumes fixos
volumes:
  cosmer_vol:
  
networks:
  meta_net:
    driver: bridge

#Services de banco mongo e postgre
services:
  srv-pyspark-notebook:
    image: zul9an9/pyspark-notebook:v4
    container_name: pyspark-notebook
    ports:
    - 8888:8888
    networks:
    - meta_net
    volumes:
    - cosmer_vol:/app