apiVersion: v1
kind: Service
metadata:
  name: srv-cosmer
spec:
  selector:
    app: srv-cosmer
  ports:
  - protocol: TCP
    port: 8888
    targetPort: 8888
    nodePort: 30000
#    protocol: TCP
#    name: http
  type: NodePort